# Generated by Django 2.0.7 on 2018-12-14 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0003_auto_20181214_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
