# Generated by Django 2.0.7 on 2018-12-15 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0004_work_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='submitted on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
