# Generated by Django 2.0.7 on 2018-12-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0005_auto_20181215_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='submitted on',
            new_name='submitted_date',
        ),
    ]
