# Generated by Django 2.0.7 on 2018-12-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0006_auto_20181215_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports'),
        ),
    ]
