# Generated by Django 2.0.7 on 2018-12-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0007_work_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='date',
            new_name='assignment_date',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='description',
            new_name='assignment_description',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='submitted',
            new_name='report_submission',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='title',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='submitted_date',
            new_name='submission_date',
        ),
    ]
